#!/bin/bash
git checkout production && \
git pull origin production && \
git push origin production && \
git checkout master && \
git pull origin master && \
git merge production && \
git push origin master && \
git checkout staging && \
git pull origin staging && \
git merge production && \
git push origin staging && \
git checkout production
