#!/usr/bin/env ruby
lines = `git branch -a | grep "#{ARGV[0]}" -i --color`.split("\n")
lines.each do |line|
	line.sub! "*", ""
	line.strip!
end
lines.each_with_index do |line, index|
	puts index.to_s + " - " + line
end
puts "q to quit"
print "Which branch: "
the_index = STDIN.gets.chomp
exit if the_index == 'q'
the_branch = lines[the_index.to_i]
the_branch.gsub!("remotes/origin/", "")
`git checkout #{the_branch}`